"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Application = require("koa");
const route = require("koa-route");
const bodyParser = require("koa-bodyparser");
const session_1 = require("../middleware/session");
const errorHandler = require("../http/error-handler");
const getGame = require("../handlers/get-game");
const getCurrentGame = require("../handlers/get-current-game");
const getCategories = require("../handlers/get-categories");
const createGame = require("../handlers/create-game");
const getCurrentQuestion = require("../handlers/get-current-question");
const useJoker = require("../handlers/use-joker");
const answerQuestion = require("../handlers/answer-question");
const finishGame = require("../handlers/finish-game");
const _createGameCommand = require("../commands/create-game");
const _getCurrentQuestionQuery = require("../queries/get-current-question");
const use_joker_1 = require("../commands/use-joker");
const answer_question_1 = require("../commands/answer-question");
const _finishGameCommand = require("../commands/finish-game");
const { get, post } = route;
function bootstrapApp(repository, dataStore) {
    const createGameCommand = _createGameCommand(repository, dataStore);
    const getCurrentQuestionQuery = _getCurrentQuestionQuery(repository, dataStore);
    const useJokerCommand = use_joker_1.useJoker(repository, dataStore);
    const finishGameCommand = _finishGameCommand(repository, dataStore);
    const answerQuestionCommand = answer_question_1.answerQuestion(repository, dataStore, finishGameCommand);
    const app = new Application();
    app.context.onerror = errorHandler;
    app.use(session_1.session(dataStore));
    app.use(bodyParser());
    app.use(get('/api/game', getCurrentGame(repository, dataStore)));
    app.use(get('/api/categories', getCategories(repository)));
    app.use(post('/api/games', createGame(repository, createGameCommand)));
    app.use(get('/api/games/:id', getGame(repository)));
    app.use(get('/api/game/question', getCurrentQuestion(getCurrentQuestionQuery)));
    app.use(post('/api/game/joker', useJoker(useJokerCommand)));
    app.use(post('/api/game/answer', answerQuestion(answerQuestionCommand)));
    app.use(post('/api/game/finish', finishGame(finishGameCommand)));
    return app;
}
exports.bootstrapApp = bootstrapApp;
//# sourceMappingURL=app.js.map